services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: laghudb
      POSTGRES_USER: laghu_user
      POSTGRES_PASSWORD: laghu_password
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
